### ISSUE TITLE
Incorrect error messages when decimation != 1

### ISSUE THREAD

**Issue by nuena** [krakenrf/heimdall_daq_fw#2]
When setting the decimation ratio to anything > 1, the log file of the decimator module will flood messages such as this one: 

> WARN  fir_decimate.c:281: Frame index missmatch. Expected 511 <--> 504 Received

where the supposed mismatch (here 511-504) is exactly (decimation - 1). I'm pretty sure this is a bug in fir_decimate.c, l. 241: 

`        expected_frame_index += dec;`

Which should be += 1 (or completely removed).

The reason I believe this is an incorrect line is that as per my understanding, the decimation will be done in the fir_decimate.c file - checking that the INCOMING index increased by steps of [decimation] does not make any sense to me - as the upstream is not "aware" of any decimation going on downstream. In addition, apart from writing a warning message, this check does not seem to do anything else. 

This check might be useful if within the rebuffer-module packets are repacked, however this is not controlled by the decimation ratio and if such a test was intended, then probably some check based on the relationship between daq_block_size and cpi_size*decimation_ratio should be used?

**Comment by krakenrf** [comment]
Thank you very much for the issue report!

In the earlier versions, this warning message was used to inform the user/developer that the throughput of the DAQ chain is insufficient, and the system is dropping IQ frames. Since the maximum load could be realized with setting the decimation ratio to 1, I have tested system always with this configuration. More complicated re-buffering and decimation settings were not handled because that would be unnecessarily too complex to implement due to the dummy frames and the possible arbitrary ratios of the cpi_size and the daq_block_size.

Since then, this feature become obsolete, because most of the modules communicate with each other on the shared memory interface, and that is able to the report the frame dropping.
To see the frame dropping messages, one may set the 
`11 #define INGORE_FRAME_DROP_WARNINGS 1,` value to 0 in _sh_mem_util.h_ and 
`38 self.ignore_frame_drop_warning = True ` value to False in _shmemIface.py_

As a consequence this log message is no longer needed, hence I have removed it.
